const { ABC_BCC_EMAIL, FLEXABILITY_BCC_EMAIL, ENABLE_CRONOFY } = require( '../config/environment');

const BUCKETS = {
  REPORT_TYPES: {
    STANDARD_NORMAL: 1,
    STANDARD_QDIRECT: 2,
    STANDARD_OMNI: 3,
  },
  CONSULTANT_TYPES: {
    RECOMMENDED: 1,
    PREFERRED: 2,
    GLOBALLY_RATED: 3,
  },
  CLIENTS_DRIVE: {
    PENDING_FEEDBACK: [
      5, 8, 17,
    ],
    SHORTLISTED: [
      34, 19, 35, 21, 24, 22, 12, 23, 33,
    ],
    FUTURE_INTERVIEW: [
      5, 8, 17,
    ],
    ALL: [
      10, 15, 20, 30, 34, 36, 42, 25, 9, 4, 1, 41, 16, 19, 35, 21, 24, 22,
      8, 17, 5, 12, 28, 29, 31, 26, 39, 18, 2, 3, 11, 14, 33, 40, 23, 38,
    ],
  },
  CLIENTS: {
    ALL: [
      10, 15, 20, 30, 34, 36, 42, 25, 9, 4, 1, 41, 16, 19, 35, 21, 24, 22,
      8, 17, 5, 12, 28, 29, 31, 26, 39, 18, 2, 3, 11, 14, 33, 40, 23, 38,
    ],
    PENDING_FEEDBACK: [
      34, 36, 42, 25, 9, 4, 1, 41, 16,
    ],
    SHORTLISTED: [
      34, 19, 35, 21, 24, 22, 8, 17, 5, 12, 23, 33,
    ],
    REJECTED: [
      18, 2, 3, 11, 14,
    ],
  },
  CONSULTANTS_ADMIN: {
    ALL: [
      43, 23, 24, 22, 33, 44, 6, 32, 19, 35, 8, 5, 17, 12, 21, 23, 25, 9, 4, 10, 15, 20, 36,
      28, 29, 30, 31, 13, 14, 2, 3, 18, 11, 39, 40, 38, 27, 41, 1, 16, 34, 26, 37, 7, 45,
    ],
    TASKS: [
      23, 24, 22, 33, 6, 32, 19, 35, 8, 5, 17, 12, 21, 43, 44,
    ],
    SHORTLISTED: [
      24, 22, 33, 19, 35, 8, 5, 17, 12, 21, 23, 42, 25, 9, 4, 10, 15, 20, 36, 28, 29, 30, 31,
    ],
    FEEDBACK: [
      25, 9, 4, 27, 7, 1, 41, 16, 34, 26, 39,
    ],
    REJECTED: [
      13, 14, 2, 3, 18, 11, 39, 40, 38, 37, 45,
    ],
  },
  CONSULTANTS: {
    ALL: [
      23, 42, 24, 22, 33, 43, 44, 6, 32, 19, 35, 8, 5, 17, 12, 21, 25, 9, 4, 10, 15, 20, 36,
      28, 29, 30, 31, 13, 14, 2, 3, 18, 11, 39, 40, 38, 27, 41, 1, 16, 34, 26, 37, 7, 45,
    ],
    TASKS: [
      23, 24, 22, 33, 6, 32, 19, 35, 8, 5, 17, 12, 21, 43, 44,
    ],
    SHORTLISTED: [
      24, 22, 33, 19, 35, 8, 5, 17, 12, 21, 23, 42, 25, 9, 4, 10, 15, 20, 36, 28, 29, 30, 31,
    ],
    FEEDBACK: [
      25, 9, 4, 27, 7, 1, 41, 16, 34, 26, 39,
    ],
    REJECTED: [
      13, 14, 2, 3, 18, 11, 39, 40, 38, 37, 45,
    ],
  },
  QUEZX: {
    ALL: [
      10, 15, 20, 30, 25, 23, 9, 4, 1, 16, 19, 21, 24,
      22, 8, 17, 5, 28, 12, 29, 31, 26, 18, 2, 3, 11, 14, 33,
    ],
    PENDING_FEEDBACK: [
      25, 23, 9, 4, 1, 16, 26,
    ],
    SHORTLISTED: [
      19, 21, 24, 22, 8, 17, 5, 12, 33,
    ],
    REJECTED: [
      18, 2, 3, 11, 14,
    ],
  },
  // Todo: Database mappings
  GROUPS: {
    GLORY_CLIENTS: 1,
    CONSULTANTS: 2,
    CANDIDATES: 3,
    INTERNAL_TEAM: 4,
    UBER_CLIENT_RECRUITERS: 5,
    NORMAL_USER: 6,
    QUEZX_AND_QUARC_CONSULTANT: 7,
    SCREENING: 8,
    ADMIN_UBER: 9,
    BUSINESS_TEAM: 10,
    INTERNAL_TEAM_UBER: 11,
    UBER_CLIENT_FINANCE: 12,
    PUBLIC_USER: 13,
    BOT: 14,
    ACCESS: 15,
  },
  USERS: {
    QBOT: {
      id: 1,
    },
    CANDIDATE: {
      id: 2,
      group_id: 11,
    },
    apply: {
      publicuser: {
        id: 0,
        app_id: 11,
        group_id: 11,
      },
    },
    partner: {
      consultantdemo: {
        id: 112,
        group_id: 2,
      },
      hthakkar: {
        id: 3269,
        group_id: 2,
      },
    },
    hire: {
      clientdemo: {
        id: 113,
        group_id: 5,
      },
    },
    manage: {
      noble: {
        id: 13,
        group_id: 4,
      },
    },
  },
  JOB_STATUS: {
    HIGH_PRIORITY: 1,
    OPEN: 2,
  },
  JOB_STATUS_NAME: {
    1: 'High Priority',
    2: 'Open',
    3: 'Hold',
    4: 'Closed',
  },
  APPLICANT_SOURCES: {
    PORTAL: 1,
    NAUKRI_EXTENSION: 2,
    MONSTER_EXTENSION: 3,
    SHINE_EXTENSION: 4,
    APPLY_QUEZX_COM: 5,
    PARTNER_CV_PAGE_REAPPLY: 6,
    SOCIAL_SHARE: 7,
    CRUX: 8,
    CHROME_EXTENSION: 9,
    CAMPUS: 11,
    CLIENT_SOCIAL_SHARE: 12,
    JOB_BOARD: 13,
    REFERRAL: 14,
    CLIENT_MANUAL_UPLOAD: 15,
    CAREER_EVENT: 16,
    MY_VENDOR_UPLOAD: 17,
    MANAGE_CV_PAGE_REAPPLY: 18,
    HIRE_CV_PAGE_REAPPLY: 19,
  },
  CV_PAGE_REAPPLY: {
    HIRE_CAMPUS: 20,
    HIRE_CLIENT_SOCIAL_SHARE: 21,
    HIRE_JOB_BOARD: 22,
    HIRE_REFERRAL: 23,
    HIRE_CLIENT_MANUAL_UPLOAD: 24,
    HIRE_CAREER_EVENT: 25,
    MANAGE_CAMPUS: 26,
    MANAGE_CLIENT_SOCIAL_SHARE: 27,
    MANAGE_JOB_BOARD: 28,
    MANAGE_REFERRAL: 29,
    MANAGE_CLIENT_MANUAL_UPLOAD: 30,
    MANAGE_CAREER_EVENT: 31,
    MANAGE_MY_VENDOR_UPLOAD: 32,
    HIRE_MY_VENDOR_UPLOAD: 33,
  },
  FOLLOWER_TYPE: {
    JD: 2,
    APPLICANT: 1,
    PROJECT: 3,
  },
  FOLLOWER_ACCESS_TYPE: {
    WRITE: 2,
    READ: 1,
  },
  APPLICANT_SOURCES_NAMES: {
    7: 'Reapply',
    11: 'Campus Channel',
    12: 'Social Media Channel',
    13: 'Job Board Channel',
    14: 'Referral Channel',
    15: 'Direct Channel',
    16: 'Career Event Channel',
    17: 'My Vendor',
  },
  STATE_NAMES: {
    1: 'Awaiting feedback on CV',
    2: 'CV Reject',
    3: 'Duplicate CV',
    4: 'Awaiting Client Input',
    5: 'Telephonic Interview',
    6: 'Screening Hold',
    7: 'CV in Pipeline',
    8: 'Personal Interview',
    9: 'Awaiting feedback on Interview',
    10: 'Make an Offer',
    11: 'Interview Backout',
    12: 'Interview Confirmed',
    13: 'Screening Reject',
    14: 'Reject',
    15: 'Offer Processing',
    16: 'Awaiting Feedback',
    17: 'Video Interview',
    18: 'Interview Reject',
    19: 'CV Shortlist',
    20: 'Offer Accepted',
    21: 'Interview Scheduling',
    22: 'Interview Scheduling Attempted',
    23: 'Interview Candidate Input Required',
    24: 'Interview Client Reschedule',
    25: 'Interview Client Confirmation Required',
    26: 'Position Hold/Closed',
    27: 'Screening Pending',
    28: 'Offer Rejected',
    29: 'Backout after Joining',
    30: 'Candidate Joined',
    31: 'Backout before Joining',
    32: 'Screening Attempted',
    33: 'Awaiting Candidate Input',
    34: 'Internal Shortlist',
    35: 'Shortlist for Next Round',
    36: 'On Hold-Interview Completed',
    37: 'Pre-Screening Reject',
    38: 'Client Backout Post Offer',
    39: 'Position on Hold',
    40: 'Position Closed',
    41: 'CV on Hold',
    42: 'Interview Cancelled',
    43: 'Pre-Screening',
    44: 'Social Share CV',
    45: 'Auto Duplicate CV',
  },
  STATES: {
    AWAITING_FEEDBACK_ON_CV: 1,
    CV_REJECT: 2,
    DUPLICATE_CV: 3,
    AWAITING_CLIENT_INPUT: 4,
    TELEPHONIC_INTERVIEW: 5,
    SCREENING_HOLD: 6,
    CV_IN_PIPELINE: 7,
    PERSONAL_INTERVIEW: 8,
    AWAITING_FEEDBACK_ON_INTERVIEW: 9,
    MAKE_AN_OFFER: 10,
    INTERVIEW_BACKOUT: 11,
    INTERVIEW_CONFIRMED: 12,
    SCREENING_REJECT: 13,
    REJECT: 14,
    SEND_TEST: 15,
    TEST_SUBMITTED: 16,
    VIDEO_INTERVIEW: 17,
    INTERVIEW_REJECT: 18,
    CV_SHORTLIST: 19,
    OFFER_ACCEPTED: 20,
    INTERVIEW_SCHEDULING: 21,
    INTERVIEW_SCHEDULING_ATTEMPTED: 22,
    INTERVIEW_CANDIDATE_INPUT_REQUIRED: 23,
    INTERVIEW_CLIENT_RESCHEDULE: 24,
    INTERVIEW_CLIENT_CONFIRMATION_REQUIRED: 25,
    POSITION_HOLD_CLOSED: 26,
    SCREENING_PENDING: 27,
    OFFER_REJECTED: 28,
    BACKOUT_AFTER_JOINING: 29,
    CANDIDATE_JOINED: 30,
    BACKOUT_BEFORE_JOINING: 31,
    SCREENING_ATTEMPTED: 32,
    AWAITING_CANDIDATE_INPUT: 33,
    INTERNAL_SHORTLIST: 34,
    SHORTLIST_FOR_NEXT_ROUND: 35,
    ON_HOLD_INTERVIEW_COMPLETED: 36,
    PRE_SCREENING_REJECT: 37,
    CLIENT_BACKOUT_POST_OFFER: 38,
    POSITION_ON_HOLD: 39,
    POSITION_CLOSED: 40,
    CV_ON_HOLD: 41,
    INTERVIEW_CANCELLED: 42,
    PRE_SCREENING: 43,
    SOCIAL_SHARE_CV: 44,
    AUTO_DUPLICATE_CV: 45,
  },
  CONSULTANT_RESPONSE: {
    ACCEPTED: 1,
  },
  CAL_MSG: {
    tokenNotFound: -7,
    deletedDueToNewEventFailed: -6,
    deletedDueToNewEvent: -5,
    rejectedDueToNewEvent: -4,
    triedAfterStartTime: -3,
    failsafeUsersExhausted: -2,
    retryLimitExceeded: -1,
    underProcessing: 0,
    sent: 1,
  },
  PREF: {
    calendarNotifications: 2,
  },
  PRODUCT: {
    2: 'partner',
    4: 'manage',
    5: 'hire',
    8: 'manage',
    9: 'manage',
    15: 'access',
  },
  OTHERS: {
    SHORTLISTED: [
      4, 5, 8, 9, 10, 11, 12, 15, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 28, 29, 30, 31, 33, 35, 36, 38, 42,
    ],
    CV_SENT: [
      2, 3, 4, 5, 8, 9, 10, 11, 12, 14, 15, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 28, 29, 30, 31, 33, 35, 36, 38, 42,
    ],
    TEST_SUBMITTED: [],
  },
  META: {
    crux: 2,
    calendar_failsafeUsers: '{"quezx0":5450,"quezx1":5451,"quezx2":5452,' +
      '"quezx3":5453,"quezx4":5455,"quezx5":5457,"quezx6":5458}',
    calendar_retryLimit: ENABLE_CRONOFY === 'true' ? -1 : 1,
    calendar_expiryGap: 5,
  },
  APPS: {
    APPLY: 11,
    CHAT_Q: 12,
    MANAGE_MOBILE: 9,
    PARTNER_WORDPRESS: 10,
    QDESK_LIVE_APP: 25,
    QTRACK: 20,
    QUEZX_ACCESS: 24,
    QUEZX_ACCOUNTS: 1,
    QUEZX_ADMIN: 5,
    QUEZX_BILLING: 28,
    QUEZX_HIRE: 3,
    QUEZX_HIRE_ANDROID: 2,
    QUEZX_HUNT: 26,
    QUEZX_MANAGE: 7,
    QUEZX_PARTNER: 4,
    QUEZX_SEARCH: 21,
    QUEZX_TEAM: 27,
    SYNTEL_IT: 19,
    ASPIRE: 6,
  },
  APP: {
    1: 1,
    2: 2,
    3: 2,
    4: 3,
    5: 1,
    7: 4,
    9: 4,
    10: 3,
    11: 5,
    12: 6,
    13: 3,
    14: 2,
    15: 4,
    19: 7,
    20: 8,
    21: 9,
    24: 10,
    25: 8,
  },

  NOTIFICATION: {
    AWAITING_FEEDBACK_ON_CV: '1',
    CV_REJECT: '2',
    DUPLICATE_CV: '3',
    AWAITING_CLIENT_INPUT: '4',
    TELEPHONIC_INTERVIEW: '5',
    SCREENING_HOLD: '6',
    PERSONAL_INTERVIEW: '8',
    AWAITING_FEEDBACK_ON_INTERVIEW: '9',
    MAKE_AN_OFFER: '10',
    INTERVIEW_BACKOUT: '11',
    INTERVIEW_CONFIRMED: '12',
    SCREENING_REJECT: '13',
    REJECT: '14',
    SEND_TEST: '15',
    TEST_SUBMITTED: '16',
    VIDEO_INTERVIEW: '17',
    INTERVIEW_REJECT: '18',
    SHORTLIST_FOR_INTERVIEW: '19',
    OFFER_ACCEPTED: '20',
    INTERVIEW_SCHEDULING: '21',
    INTERVIEW_SCHEDULE_ATTEMPT: '22',
    INTERVIEW_CANDIDATE_INPUT_REQUIRED: '23',
    INTERVIEW_CLIENT_RESCHEDULE: '24',
    INTERVIEW_CLIENT_CONFIRMATION_REQUIRED: '25',
    POSITION_HOLD_CLOSED: '26',
    SCREENING_PENDING: '27',
    OFFER_REJECTED: '28',
    CANDIDATE_JOINED: '30',
    BACKOUT_AFTER_JOINING: '31',
    SCREENING_ATTEMPTED: '32',
    AWAITING_CANDIDATE_INPUT: '33',
    SHORTLIST_FOR_EVALUATION: '34',
    SHORTLIST_FOR_NEXT_ROUND: '35',
    JD_REJECTED: '101',
    JD_ACCEPTED: '102',
    NEW_CVS: '103',
    JOINING_FOLLOW_UP: '104',
    JD_PRIORITY: '105',
    ANNOUNCEMENT: '106',
    ARCHIVED: '107',
    COMMENT: '108',
    NEW_JD_UPDATE: '110',
    HIDDEN_JD: '111',
  },
  CHANNEL_SOURCES: {
    QUEZX_PARTNER: 1,
    MY_VENDOR: 2,
    REFERRAL: 3,
    SOCIAL: 4,
    JOB_BOARD: 5,
    CAMPUS: 6,
    HIRE_MANUAL_UPLOAD: 7,
    CAREER_EVENT: 8,
  },
  QUEZX_APPS: {
    OMNI: 1,
    CLOSED_COMMERCIAL: 2,
  },
  JOB_PORTALS: {
    HH: 1,
  },
  EXHAUSTIVE_REPORTS: {
    STATES: [
      1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
      28, 29, 30, 31, 33, 34, 35, 36, 38, 39, 40, 41, 42,
    ] },
  JOB_META: {
    PANELIST: 'panelist',
    BULLHORN_JOB_ID: 'bullhorn_job_id',
    REFERRAL_URL: 'referral_url',
    SOCIAL_URL: 'social_url',
    JOB_BOARD_URL: 'job_board_url',
    CAMPUS_URL: 'campus_url',
    CAREER_EVENT_URL: 'career_event_url',
    DIRECT_LINEUP_AUTO_SHORTLIST: 'direct_lineup_auto_shortlist',
    DIRECT_LINEUP_AUTO_SHORTLIST_DATE: 'direct_lineup_auto_shortlist_date',
    DIVERSITY_AND_INCLUSION: 'diversity_and_inclusion',
    QREX_COMPANY: 'qrex_company',
    JOB_TEMPLATE_ANALYTICS: 'job_template_analytics',
    JOB_COMPLETION_PERCENTAGE: 'job_completion_percentage',
  },
  JOB_META_OMNI_CHANNELS: {
    REFERRAL_URL: 'referral_url',
    SOCIAL_URL: 'social_url',
    JOB_BOARD_URL: 'job_board_url',
    CAMPUS_URL: 'campus_url',
    CAREER_EVENT_URL: 'career_event_url',
  },
  APPLICANT_META: {
    BULLHORN_APPLICANT_ID: 'bullhorn_applicant_id',
    BGC: 'bgc',
  },
  ADDRESS_TYPE: {
    INTERVIEW: 'interview',
  },
  APPLICANT_STATE_META: {
    INTERVIEW_ADDRESS: 'interview_address',
  },
  FACTOR_TYPE: {
    CV_FEEDBACK_FACTOR: 'cv_feedback_factor',
    INTERVIEW_FEEDBACK_FACTOR: 'interview_feedback_factor',
  },
  USER_TYPE: {
    1: 'CLIENT',
    2: 'CONSULTANT',
  },
  LEAD_CATEGORY: {
    1: 'Cold',
    2: 'Warm',
    3: 'Hot',
  },
  UTM_SOURCE: {
    1: 'consultant',
    2: 'client',
  },
  UTM_SOURCE_KEYS: {
    UTM_SOURCE: 'utm_source',
    UTM_MEDIUM: 'utm_medium',
    UTM_CAMPAIGN: 'utm_campaign',
    UTM_CONTENT: 'utm_content',
  },
  CLIENT_TYPE: {
    STARTUP: 'STARTUP',
    SME: 'SME',
    ENTERPRISE: 'ENTERPRISE',
  },
  KUE_META: {
    EMAIL: 'email',
    WHATSAPP: 'whatsapp',
  },
  CUSTOM_FIELDS: {
    TEXTBOX: 'textbox',
    TEXTAREA: 'textarea',
  },
  HARDCODED_CLIENT_ID: {
    3635: ABC_BCC_EMAIL,
    3780: FLEXABILITY_BCC_EMAIL,
  },
  DEFAULT_STATUS: {
    DEFAULT: 'disabled',
    ENABLED: 'enabled',
    EARNED: 'earned',
  },
  PAYOUT_TYPE: {
    FIXED: 'fixed',
    LUCKY: 'lucky',
  },
  DIVERSITY: {
    1: {
      id: '1',
      icon: 'female-icon',
      name: 'All Female Candidates',
      primaryColor: '#6d3d8e',
      secondaryColor: '#7d4b9e',
    },
    2: {
      id: '2',
      icon: 'shield-icon',
      name: 'War Veterans (Defence)',
      primaryColor: '#6d3d8e',
      secondaryColor: '#7d4b9e',
    },
    3: {
      id: '3',
      icon: 'women-icon',
      name: 'Women Re-Joining Workforce',
      primaryColor: '#6d3d8e',
      secondaryColor: '#7d4b9e',
    },
    4: {
      id: '4',
      icon: 'abled-icon',
      name: 'Differently-abled',
      primaryColor: '#6d3d8e',
      secondaryColor: '#7d4b9e',
    },
    5: {
      id: '5',
      icon: 'pride-icon',
      name: 'Pride (for LGBTQ)',
      primaryColor: '#6d3d8e',
      secondaryColor: '#7d4b9e',
    },
  },
  FEEDBACK_META: {
    CLIENT_RATING: 'client_rating',
  },
  CLIENT_META: {
    ACCOUNTS_TEAM_EMAIL_ID: 'accounts_team_email_id',
    FIN_MGR_ID: 'fin_mgr_id',
    OMNI_PLUGIN: 'omni_plugin',
  },
  FEEDBACK_TYPE: {
    THREE_AND_LESS_RATING: 6,
    FOUR_RATING: 7,
    FIVE_RATING: 8,
  },
  INTERVIEW_BACKOUT: {
    FOLLOWUP_OPTIONS: {
      TELEPHONIC: 2,
      PERSONAL: 5,
      VIDEO: 8,
    },
  },
  AGREEMENT_MODELS: {
    ROLE: 'role',
    CTC: 'ctc',
  },
  CLIENT_APPS: {
    CLIENT_MANAGEMENT: 10,
  },
};


module.exports = BUCKETS;
